### ISSUE TITLE
wchtools push or npm run build-deploy not valid WCH request

### ISSUE THREAD

**Issue by artsmorgan** [ibm-wch/wchtools-cli#49]
Hello, i'm trying to push my contents into WCH but when i use the build-deploy command or wchtools push i got an error

The path [/api/delivery/v1/rendering/sites/default/login/v1/basicauth] is not a valid Watson Content Hub request.

It prompts the email that i'm using in Watson Content Hub then ask for password, but when i write the same password that i'm using in WCH give the error.

if i type the url in the browser i get:

```
{
  "requestId": "e815057367e7868e30a5f6301a784af1",
  "service": "prod-infra-api-dispatcher",
  "version": "0.0.1470",
  "description": "IBM Watson Content Hub, API Dispatcher Component",
  "errors": [
    {
      "name": "NotFoundError",
      "message": "The path [/api/delivery/v1/rendering/sites/login/v1/basicauth] is not a valid Watson Content Hub request.",
      "locale": "en",
      "parameters": {
        "statusCode": 404,
        "path": "/api/delivery/v1/rendering/sites/login/v1/basicauth",
        "timestamp": 1562006752163
      },
      "timestamp": "Mon, 01 Jul 2019 18:45:52 GMT"
    }
  ],
  "timestamp": "Mon, 01 Jul 2019 18:45:52 GMT",
  "message": "The path [/api/delivery/v1/rendering/sites/login/v1/basicauth] is not a valid Watson Content Hub request."
}
```

**Comment by mburati** [comment]
@artsmorgan - I suggest checking the WCH API URL that you configured wchtools with,  it looks like that may have been set incorrectly.   If you run wchtools init it should look something like:

https://my6.digitalexperience.ibm.com/api/########-####-####-####-############

ending with your unique WCH tenant id, in place of those #s.    From the WCH Authoring UI, go to the lower left "About" menu then "Hub Information"  to copy your WCH "API URL" and then use that to set the API URL via the wchtools init command.

I hope that information helps,
..Mike

**Comment by artsmorgan** [comment]
Thanks Mike, it worked.
